# tasks file for nutanix_role_nutanix_proxy
- name: Check nutanix_proxy_name is provided
  ansible.builtin.fail:
    msg: var nutanix_proxy_name is required
  when:
    - nutanix_proxy_name is not defined

- name: Check nutanix_proxy_address is provided
  ansible.builtin.fail:
    msg: var nutanix_proxy_address is required
  when:
    - nutanix_proxy_address is not defined

- name: Check nutanix_proxy_port is provided
  ansible.builtin.fail:
    msg: var nutanix_proxy_port is required
  when:
    - nutanix_proxy_port is not defined

- name: Check nutanix_proxy_types is provided
  ansible.builtin.fail:
    msg: var nutanix_proxy_types is required
  when:
    - nutanix_proxy_types is not defined

- name: Setup connection to Nutanix API
  ansible.builtin.include_tasks: setup_api.yml

- name: Inputs for proxy server task
  ansible.builtin.include_tasks: proxy.yml

- name: Inputs for proxy server whitelist task
  ansible.builtin.include_tasks: whitelist.yml
  when: nutanix_proxy_whitelist | length > 0

- name: Debug
  ansible.builtin.include_tasks: debug.yml
  when:
    - nutanix_debug
