---
- name: Gather proxy configuration from cluster
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/http_proxies"
    method: GET
    validate_certs: "{{ role_nutanix_prism_proxy_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_prism_proxy_current_config

- name: Debug role_nutanix_prism_proxy_current_config
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_current_config }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_current_config is defined

- name: Compare current proxy name to new proxy name
  ansible.builtin.set_fact:
    role_nutanix_prism_proxy_name_mismatch:
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - role_nutanix_prism_proxy_current_config.json.entities[0].name != role_nutanix_prism_proxy_name

- name: Debug role_nutanix_prism_proxy_name_mismatch
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_name_mismatch }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_name_mismatch is defined

- name: Compare current proxy config to new proxy config
  ansible.builtin.set_fact:
    role_nutanix_prism_proxy_mismatch:
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - ( role_nutanix_prism_proxy_current_config.json.entities[0].address != role_nutanix_prism_proxy_address or
      role_nutanix_prism_proxy_current_config.json.entities[0].port != role_nutanix_prism_proxy_port or
      role_nutanix_prism_proxy_current_config.json.entities[0].username != role_nutanix_prism_proxy_username | default(None) )

- name: Debug role_nutanix_prism_proxy_mismatch
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_mismatch }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_mismatch is defined

- name: Compare configured proxy types to defined proxy types
  ansible.builtin.set_fact:
    role_nutanix_prism_proxy_extra_type:
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - item not in role_nutanix_prism_proxy_types
  with_items: "{{ role_nutanix_prism_proxy_current_config.json.entities[0].proxy_types }}"

- name: Debug role_nutanix_prism_proxy_extra_type
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_extra_type }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_extra_type is defined

- name: Compare defined proxy types to configured proxy types
  ansible.builtin.set_fact:
    role_nutanix_prism_proxy_missing_type:
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - item not in role_nutanix_prism_proxy_current_config.json.entities[0].proxy_types
  with_items: "{{ role_nutanix_prism_proxy_types }}"

- name: Debug role_nutanix_prism_proxy_missing_type
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_missing_type }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_missing_type is defined

- name: Delete prism proxy configuration to fix name mismatch
  ansible.builtin.uri:
    url:
      "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/http_proxies/\
      {{ role_nutanix_prism_proxy_current_config.json.entities[0].name }}"
    method: DELETE
    validate_certs: "{{ role_nutanix_prism_proxy_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 204
    return_content: true
  changed_when: true
  register: role_nutanix_prism_proxy_deleted
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - role_nutanix_prism_proxy_name_mismatch is defined

- name: Debug role_nutanix_prism_proxy_deleted
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_deleted }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_deleted is defined

- name: Create proxy configuration
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/http_proxies"
    method: POST
    validate_certs: "{{ role_nutanix_prism_proxy_host_validate_certs }}"
    body: "{{ lookup('template', 'proxy.j2') | from_yaml | to_json }}"
    body_format: json
    status_code: 201
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_prism_proxy_create
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 0 or role_nutanix_prism_proxy_name_mismatch is defined

- name: Debug role_nutanix_prism_proxy_create
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_create }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_create is defined

- name: Update proxy configuration
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/http_proxies"
    method: PUT
    validate_certs: "{{ role_nutanix_prism_proxy_host_validate_certs }}"
    body: "{{ lookup('template', 'proxy.j2') | from_yaml | to_json }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_prism_proxy_update
  changed_when: role_nutanix_prism_proxy_update.json.value == true
  when:
    - role_nutanix_prism_proxy_current_config.json.metadata.count == 1
    - role_nutanix_prism_proxy_name_mismatch is not defined
    - role_nutanix_prism_proxy_mismatch is defined

- name: Debug role_nutanix_prism_proxy_update
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_update }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_update is defined

- name: Wait HTTP proxy update to be completed
  block:
    - name: Checking HTTP proxy configuration
      ansible.builtin.uri:
        url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/http_proxies"
        method: GET
        validate_certs: "{{ role_nutanix_prism_proxy_host_validate_certs }}"
        status_code: 200
        headers:
          Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
      register: role_nutanix_prism_proxy_status
      until:
        - role_nutanix_prism_proxy_status.json.entities[0].name == role_nutanix_prism_proxy_name
        - role_nutanix_prism_proxy_status.json.entities[0].address == role_nutanix_prism_proxy_address
        - role_nutanix_prism_proxy_status.json.entities[0].port == role_nutanix_prism_proxy_port
        - role_nutanix_prism_proxy_status.json.entities[0].username == role_nutanix_prism_proxy_username | default(None)
      retries: 60
      delay: 10
      when: role_nutanix_prism_proxy_create is defined or role_nutanix_prism_proxy_update is defined

- name: Debug role_nutanix_prism_proxy_status
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_proxy_status }}"
  when:
    - role_nutanix_prism_proxy_debug
    - role_nutanix_prism_proxy_status is defined
